import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'
import { ClerkProvider, auth, useClerk } from '@clerk/nextjs'
import { dark, shadesOfPurple } from '@clerk/themes';
import { deDE } from "@clerk/localizations";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId } = auth();
  return (  
    <ClerkProvider>
      <html lang="en">
        <body className= "h-screen overflow-hidden">
        {userId && <Nav />}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
